### ISSUE TITLE
Board is not responding

### ISSUE THREAD

**Issue by fsmosca** [eligolf/affinity_chess#1]
I tried to run it in windows 10, but the board is no responding. How do you make it play?

**Comment by eligolf** [comment]
The AI takes around 10 seconds for the first move if you run at depth 6. You can chose a lower level (try medium for example) and it should play immediately. I uploaded a new version where you can chose options from a start-up window. Try again and see if it works now.

**Comment by fsmosca** [comment]
Thanks it is working now.
