### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by fsmosca** [eligolf/affinity_chess#3]
Played a game against the ai and its memory keeps on rising after every move of ai. It reaches around 2.1 GB just before the game ends.

`1.d4 e6 2.c4 Nc6 3.Nf3 Bb4+ 4.Nc3 Bxc3+ 5.bxc3 Nf6 6.Bg5 h6 7.Bh4 g5 8.Bg3 Ne4 9.Qc2 Nxg3 10.hxg3 g4 11.Nd2 e5 12.e3 Qf6 13.Bd3 Rb8 14.O-O O-O 15.f3 Qg5 16.f4 exf4 17.Rxf4 Re8 18.e4 Qg7 19.Rf1 d6 20.Nb3 Qg5 21.Qf2 f5 22.Nd2 Qh5 23.exf5 Bd7 24.Ne4 Rf8 25.f6 Qf7 26.Qd2 Re8 27.Rf2 h5 28.Qg5+ Kh8 29.Qh6+ Qh7 30.Qxh7+ Kxh7 31.Nxd6+ Kh8 32.Nxe8 Rxe8 33.Bg6 Rf8 34.Bxh5 Na5 35.Re1 Kh7 36.Re7+ Kh6 37.Rxd7 Kxh5 38.Rxc7 Nxc4 39.Rxc4 Kg6 40.Rc7 Rxf6 41.Rxf6+ Kxf6 42.Rxb7 a 6 43.Rb6+ Kf5 44.Rxa6 Ke4 45.Rc6 Ke3 46.a4 Ke4 47.a5 Kd5 48.Rc5+ Ke4 49.a6 Kd3 50.a7 Ke2 51.a8=Q Ke3 52.Qa2 Kd3 53.Kf2 Ke4`

Played another game and after around 18 moves restarted the game with r key and the used memory after 18 moves was still there and the memory used still increases for this restarted game.

**Comment by eligolf** [comment]
This is probably due to the transposition table. Do you think it would solve the problem by clearing cahce at new game like this? 

from streamlit import caching
caching.clear_cache()

**Comment by fsmosca** [comment]
You can try clearing the table for every new game and see what happens to memory. But the issue of increasing memory after the ai thinks about the positions should be checked first as it is reaches 2GB in that 53-move game.

You can disable the table and check if there is leak, if there is none then it must be the table.

You have some updates, memory check has to be checked again.

**Comment by eligolf** [comment]
Fixed, was a leak in the valid_moves_history table. Thank you once again for spotting this.
