### ISSUE TITLE
Hardware/Software requirements for running?

### ISSUE THREAD

**Issue by rwbc** [eligolf/affinity_chess#6]
Hi Elias,

I tried your GUI/AI w/o success on my old Win7-64 quadcore with Python 3.86 and pypy37 (via batch)
but after creating pycache with gamestate and settings it closes always? Any idea?

Edit:
Tried now via cmd directly from the Python path and can see this error:

pygame is not in the repo - where to get it?

```
C:\Python386>python C:\Affinity_Chess\gui.py
Traceback (most recent call last):
  File "C:\Affinity_Chess\gui.py", line 4, in <module>
    import gamestate as gs
  File "C:\Affinity_Chess\gamestate.py", line 5, in <module>
    import settings as s
  File "C:\Affinity_Chess\settings.py", line 3, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'
```

Guenther (RWBC)

**Comment by eligolf** [comment]
Hi, sorry but I should write that as a requirement, you need to install pygame to run. You can install it in your CMD with 'pip install pygame' if you have pip installed on your computer. 

I would suggest you try my better engine which you can find here: https://github.com/eligolf/endamat_chess. I still have to write a ReadMe for that which I will do after the weekend. In the 'exe' folder you will find the program which you can load into your own GUI (e.g. Arena or any other GUI that supports UCI engines).

**Comment by rwbc** [comment]
Sorry for the late reply. I did not want to press you to create a new public repo.
But as it is there now, should it be considered as a pre-release of your uci engine?

Or do you want to announce an official release later, otherwise I would add it
already to the XB/UCI chronology.
https://docs.google.com/spreadsheets/d/1GXoy3lGhdKPJbatdw2_2dhWT3TkpthPcNtHs51MQydM

**Comment by eligolf** [comment]
Not at all, it was already in the making! :) 

I am not sure what that is, but if you want you can add the one I linked to in the previous comment. It is now updated with a better ReadMe too. Thanks!

**Comment by rwbc** [comment]
Hi

> 
> 
> Not at all, it was already in the making! :)
> 
> I am not sure what that is, but if you want you can add the one I linked to in the previous comment. It is now updated with a better ReadMe too. Thanks!

Hi again,

It is basically a list for all available XB/UCI engines (w/o stupid derivates clones etc, see TOC) ever released.
This is probably one of the main resources for all testers,collectors,programmers and whoever is interested in this part of computerchess, espcially after CCW seems deceased.
(http://www.computer-chess.org/doku.php?id=computer_chess:wiki:lists:chess_engine_list)
Also it is running much longer than all other resources (since 2002 with a break from 2010-2015 and revived in 2016)

So if it is added as a program there, people will start downloading and testing it and I will also announce it at talkchess.

Two questions moreover, the 'exe' of your program calls itself still affinity chess, but the repo is 'endamat'.
What should be its name? Also it has no version attached currently. And last not least, what's your nationality,
I guess Elias Nilsson is your real name (sounds Swedish?)?
I want to attach the proper informations, which are needed (anonymous entries are not possible).

Thanks :)

**Comment by eligolf** [comment]
Cool! I will have a look at them, should be lots of nice inspiration there. 

Sorry about the exe, good catch! It is now changes and updated. And you are right, it is Swedish :)

**Comment by rwbc** [comment]
> 
> 
> Cool! I will have a look at them, should be lots of nice inspiration there.
> 
> Sorry about the exe, good catch! It is now changes and updated. And you are right, it is Swedish :)

I guess we have a slight missunderstanding about the exe. ;-)
Of course I meant this (internally naming and no version number - I can still use the release date though,
but it should be clear what its real name is now, so either affinity or endamat?)

```
uci
id name Affinity Chess
id author Elias Nilsson
uciok

```

**Comment by eligolf** [comment]
I know what you mean, I updated both exe and uci.py :) You can go with Endamat

**Comment by rwbc** [comment]
> 
> 
> I know what you mean, I updated both exe and uci.py :) You can go with Endamat

Ah but my download after your previous message, did not reflect this?

**Comment by eligolf** [comment]
Strange, I updated this 3 hours ago in the uci.py file. Did you download from Endamat repository and not this one that we are currently writing in?

**Comment by rwbc** [comment]
> 
> 
> Strange, I updated this 3 hours ago in the uci.py file. Did you download from Endamat repository and not this one that we are currently writing in?

I downloaded it again and also looked into uci.py.
The exe has the old name (internally - like posted), the py file is renamed :)

**Comment by eligolf** [comment]
Hmm.. Works on my computer, I tried to run the local file which puts the right name out. Deleted and reuploaded on Github, if that doesn't work then I don't know what is going on. Sorry about all these issues

**Comment by rwbc** [comment]
Now it works as it should, the exe (now endamat.exe) calls itself internally endamat. :)

```
uci
id name Endamat Chess
id author Elias Nilsson
uciok

```

I will add it later today to the XB/UCI chronology and also write a little note in the engine releases thread.
Of course you should perhaps also say a little bit in an own thread, as a member of talkchess ;-)

Thanks for the release and fix!
